name: BungeeTabListPlus
main: codecrafter47.bungeetablistplus.BukkitPlugin
version: ${project.version}
authors:
  - CodeCrafter47
softdepend: [Factions, Vault, VanishNoPacket, SuperVanish, PremiumVanish, PlayerPoints, PlaceholderAPI]
